### ISSUE TITLE
Freeling doesn't yield compositional time expressions

### ISSUE THREAD

**Issue by olzama** [delph-in/srg#18]
See e.g. item 831 in the MRS test suite; something like "10 minutes" will be fused into a "time expression": "tm_min:10", which is not what we want. So, Freeling's output should be overridden in such cases (in a non-trivial way). To see: whether there are any alternative tokenizations available via the Freeling API.

**Comment by olzama** [comment]
Thanks, I will try to figure out how!

**Comment by olzama** [comment]
The same concerns dates, e.g. in item 941: "3_de_junio"

**Comment by arademaker** [comment]
See https://freeling-user-manual.readthedocs.io/en/latest/modules/maco/. The Python API example can help too:

https://github.com/TALP-UPC/FreeLing/blob/master/APIs/python3/sample.py#L113-L145
