### ISSUE TITLE
Named entities and uppercase (and freeling)

### ISSUE THREAD

**Issue by olzama** [delph-in/srg#34]
The tokenizer that I am currently using will treat uppercase things (LA PÉRGOLA, SEIS MESES) as named entities. In the actual TIBIDABO treebank, e.g. in its portion which consists of two-word sentences, most examples do not represent named entities though some do.

I think perhaps the way to go is to let Freeling do its thing and to put the responsibility for lowercasing things on the corpus creator? But in the original version of the treebanks, all items were analyzed as compositional and were tokenized.

**Comment by arademaker** [comment]
Which NER module are you using? The BASIC is very limited, the BIO is trainable 

https://freeling-user-manual.readthedocs.io/en/v4.1/modules/ner/

**Comment by olzama** [comment]
@arademaker yes, thank you, that does change the behavior to the better!
