### ISSUE TITLE
Some ambiguity should remain after Freeling analysis

### ISSUE THREAD

**Issue by olzama** [delph-in/srg#69]
In `sppp.dat`/ `util/freeling_api/srg-freeling.dat` in the ReplaceAll section, there are multiple possibilities for some words, and all of these possibilities should remain somehow:

```
menos menos AQ0CS00 menos SP menos RG
```

I don't know at the moment how to do this, because we only expect one YY-input per item? But somehow, the goal is to have all these three tag possibilities for the orthography _menos_...

**Comment by olzama** [comment]
Is there an example somewhere of what the result would look like? 

from https://github.com/delph-in/docs/wiki/PetInput :
```
(id, start, end, [link,] path+, form [surface], ipos, lrule+ [, {pos p}+])

(46, 4, 5, <28:36>, 1, "exercise", 0, "null", "NN" 0.9887 "VB" 0.0113)
```

The above assumes in-built morphology I think. In my case, I need the name of the lexical rule (or in some cases, sequence of rules):

```
(1, 0, 1, <0:13>, 1, "explicación" "explicaciones", 0, "ncfp000", "ncfp000" 1.00000000) (2, 1, 2, <14:23>, 1, "oficial" "oficiales", 0, "aq0cp00", "aq0cp00" 0.96039604)
```

What is not clear to me is, what do I do with the lexical rule name if I want a sequence of POS tags with probabilties? Can I then also have a sequence of lexical rule names with the same probabilities? I don't think so? But each tag only makes sense with the corresponding lexical rule name in the SRG (the whole poing of those tags is to be mapped to the lexical rules).

Ace does not like:

```
(1, 0, 1, <0:13>, 1, "explicación" "explicaciones", 0, "ncfp000", "ncfp000" 1.00000000) (2, 1, 2, <14:23>, 1, "oficial" "oficiales", 0, "aq0cp00" 0.96039604, "aq0cp00" 0.96039604)
expected ')', but input is 0.96039604, "aq0
```

**Comment by fcbond** [comment]
Hi,

I think you need to make two entries with the same start and end points:

> (1, 0, 1, <0:13>, 1, "explicación" "explicaciones", 0, "ncfp000", "ncfp000" 1.00000000) 
> (2, 1, 2, <14:23>, 1, "oficial" "oficiales", 0, "aq0cp00", "aq0cp00" 0.96039604)
> (3, 1, 2, <14:23>, 1, "oficial" "oficiales", 0, "XXXYYY", "XXXYYY" 0.00001)

Then it will try to makes parses spanning either token 2 or 3.

**Comment by olzama** [comment]
Aha, thanks!! I will add this example to the wiki.

**Comment by olzama** [comment]
Should probably add more exceptions. In particular, seems like more ambiguity is useful in almost all forms of *ser* and *estar*, or at least in *está*.

**Comment by olzama** [comment]
Maybe also the problem with ordinal numbers stems from here; try adding "primero" to exceptions...

**Comment by olzama** [comment]
Also dar, especially _da_ because of _da igual_.

**Comment by olzama** [comment]
This is fixed in the freeling interface script.
